# Site settings
title: 刚子
baseurl: ""
url: "http://liaogang.github.io"

highlighter: rouge


# Build settings
markdown: kramdown
theme: minima
# remote_theme: jekyll/minima


plugins:
  - jekyll-feed


# Build settings
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# permalink: pretty

#　禁用自定义插件
# safe: true

# default values
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values: 
      layout: "post_center"
      post_width: "900"
      # image_server_base: "https://coding.net/u/liaogang123/p/ImageServer/git/raw/master/"
      image_server_base: "http://127.0.0.1:4000/resource/img/"
